//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/[Game]/InputSystem/DragDropControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @DragDropControl : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @DragDropControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""DragDropControl"",
    ""maps"": [
        {
            ""name"": ""MainMap"",
            ""id"": ""ed57e2fe-868a-4349-b381-871300e99013"",
            ""actions"": [
                {
                    ""name"": ""Drag&Drop"",
                    ""type"": ""Button"",
                    ""id"": ""44920a10-985a-409c-885c-384207ce821d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9bfea6dc-a04b-4d91-9460-627419aa9077"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": ""Hold(duration=0.5,pressPoint=0.5)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drag&Drop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MainMap
        m_MainMap = asset.FindActionMap("MainMap", throwIfNotFound: true);
        m_MainMap_DragDrop = m_MainMap.FindAction("Drag&Drop", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MainMap
    private readonly InputActionMap m_MainMap;
    private IMainMapActions m_MainMapActionsCallbackInterface;
    private readonly InputAction m_MainMap_DragDrop;
    public struct MainMapActions
    {
        private @DragDropControl m_Wrapper;
        public MainMapActions(@DragDropControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @DragDrop => m_Wrapper.m_MainMap_DragDrop;
        public InputActionMap Get() { return m_Wrapper.m_MainMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainMapActions set) { return set.Get(); }
        public void SetCallbacks(IMainMapActions instance)
        {
            if (m_Wrapper.m_MainMapActionsCallbackInterface != null)
            {
                @DragDrop.started -= m_Wrapper.m_MainMapActionsCallbackInterface.OnDragDrop;
                @DragDrop.performed -= m_Wrapper.m_MainMapActionsCallbackInterface.OnDragDrop;
                @DragDrop.canceled -= m_Wrapper.m_MainMapActionsCallbackInterface.OnDragDrop;
            }
            m_Wrapper.m_MainMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @DragDrop.started += instance.OnDragDrop;
                @DragDrop.performed += instance.OnDragDrop;
                @DragDrop.canceled += instance.OnDragDrop;
            }
        }
    }
    public MainMapActions @MainMap => new MainMapActions(this);
    public interface IMainMapActions
    {
        void OnDragDrop(InputAction.CallbackContext context);
    }
}
